name: ci-cloudflare-pages
on:
  push:
    branches: [main]
    paths:
      - 'packages/cloudflare-pages/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/cloudflare-pages/**'

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cloudflare-pages
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test

  ci-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./packages/cloudflare-pages
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn test
