name: ci-cloudflare-pages
on:
  push:
    branches: [main]
    paths:
      - 'packages/cloudflare-pages/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/cloudflare-pages/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cloudflare-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: yarn install
      - run: yarn build
      - run: yarn test

  ci-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./packages/cloudflare-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: yarn install
      - run: yarn test
